version: '3.9'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - 5672:5672

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432